# Analysis of experiment #1: DPCP heuristics

## Data

In [20]:
# Read csv

import pandas as pd

df = pd.read_csv("out/stats.csv")

# Some renames to improve readability
df["solver"] = df["solver"].str.replace("v2", "deg")
df["solver"] = df["solver"].str.replace("v3", "edg")

# For the unsolved instances,
# --> write NaN in ub
# --> write NaN in bestTime
# --> write NaN in bestIter
df.loc[df.state != "FEASIBLE", "ub"] = float("nan")
df.loc[df.state != "FEASIBLE", "bestTime"] = float("nan")
df.loc[df.state != "FEASIBLE", "bestIter"] = float("nan")

# Rename some columns
df = df.rename(columns={'ub': 'value', 'state': 'solved'})

df

,instance,solver,run,nvertices,nedges,nA,nB,nvars,ncons,solved,...,otherNodesNColsHeur,otherNodesNColsMwis1,otherNodesNColsMwis2,otherNodesNColsExact,otherNodesTime,otherNodesTimePool,otherNodesTimeHeur,otherNodesTimeMwis1,otherNodesTimeMwis2,otherNodesTimeExact
0,r_n100_p0.25_nA20_nB20_i0,heur_greedy2s_deg,0,100,1186,20,20,-1,-1,FEASIBLE,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1,r_n150_p0.75_nA15_nB15_i2,heur_greedy2s_deg,0,150,8450,15,15,-1,-1,FEASIBLE,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,r_n150_p0.25_nA15_nB15_i2,heur_greedy2s_deg,0,150,2737,15,15,-1,-1,FEASIBLE,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,r_n150_p0.75_nA15_nB30_i1,heur_greedy2s_deg,0,150,8396,15,30,-1,-1,FEASIBLE,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
4,r_n150_p0.5_nA15_nB30_i2,heur_greedy2s_deg,0,150,5571,15,30,-1,-1,FEASIBLE,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
643,r_n100_p0.25_nA20_nB10_i0,heur_greedy1s,0,100,1254,20,10,-1,-1,INFEASIBLE,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
644,r_n150_p0.5_nA30_nB15_i1,heur_greedy1s,0,150,5532,30,15,-1,-1,INFEASIBLE,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
645,r_n100_p0.75_nA10_nB20_i1,heur_greedy1s,0,100,3752,10,20,-1,-1,FEASIBLE,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
646,r_n150_p0.25_nA30_nB30_i0,heur_greedy1s,0,150,2776,30,30,-1,-1,FEASIBLE,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
647,r_n100_p0.5_nA20_nB20_i1,heur_greedy1s,0,100,2488,20,20,-1,-1,FEASIBLE,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

## Summary

In [21]:
df2 = df.groupby(["nvertices","solver"]).agg(
    {
        "solved": [("count", lambda x: (x == "FEASIBLE").sum())],
        "value": [("avg", "mean")],
        "time": [("avg", "mean")],
        "bestIter": [("avg", "mean")]
    }
).reset_index()
df2

,nvertices,solver,solved,value,time,bestIter
,,,count,avg,avg,avg
0,100,heur_greedy1s,28,3.285714,0.007961,0.000000
1,100,heur_greedy2s_deg,36,4.638889,0.002705,0.000000
2,100,heur_greedy2s_edg,35,4.200000,0.002054,0.000000
3,100,heur_semigreedy2s_deg_r10,36,4.083333,0.005738,1.083333
4,100,heur_semigreedy2s_deg_r100,36,3.666667,0.051427,11.333333
5,100,heur_semigreedy2s_deg_r1000,36,3.472222,0.426666,69.388889
6,100,heur_semigreedy2s_edg_r10,36,3.638889,0.003400,2.222222
7,100,heur_semigreedy2s_edg_r100,36,3.333333,0.029700,14.111111
8,100,heur_semigreedy2s_edg_r1000,36,3.194444,0.272722,61.916667
9,150,heur_greedy1s,26,4.269231,0.021848,0.000000
10,150,heur_greedy2s_deg,34,6.000000,0.006077,0.000000
11,150,heur_greedy2s_edg,34,5.941176,0.005483,0.000000
12,150,heur_semigreedy2s_deg_r10,34,5.205882,0.019234,2.000000
13,150,heur_semigreedy2s_deg_r100,35,4.971429,0.161453,13.114286
14,150,heur_semigreedy2s_deg_r1000,36,5.055556,1.377694,83.694444
15,150,heur_semigreedy2s_edg_r10,35,5.400000,0.013817,1.457143
16,150,heur_semigreedy2s_edg_r100,35,4.942857,0.104780,21.285714
17,150,heur_semigreedy2s_edg_r1000,35,4.657143,0.977151,158.171429