# Analysis of experiment #1: DPCP heuristics

## Read data

In [1]:
# Read csv

import pandas as pd

df = pd.read_csv("stats3.csv")

# Remove semigreedy rows
df = df[~df.solver.str.contains("semigreedy")]

# Some renames to improve readability
df["solver"] = df["solver"].str.replace("v1", "DEG")
df["solver"] = df["solver"].str.replace("v2", "QDEG")
df["solver"] = df["solver"].str.replace("v3", "SQDEG")

# For the unsolved instances,
# --> write NaN in ub, bestTime, bestIter
df.loc[df.state != "FEASIBLE", "value"] = float("nan")
df.loc[df.state != "FEASIBLE", "bestTime"] = float("nan")
df.loc[df.state != "FEASIBLE", "bestIter"] = float("nan")

# Rename some columns
df = df.rename(columns={'state': 'status'})

# Add column with edge probability
df["p"] = df.instance.apply(lambda s: float(s.split("_")[2][1:]))

# Rename heuristic names
df["solver"] = df["solver"].replace({
    "heur_greedy2s_DEG": "greedy 2-step (DEG)",
    "heur_greedy2s_QDEG": "greedy 2-step (QDEG)",
    "heur_greedy2s_SQDEG": "greedy 2-step (SQDEG)",
    "heur_greedy1s": "greedy 1-step",
})

# Convert time to miliseconds
df["totalTime"] = df["totalTime"] * 1e3

# Replace nan in value with min(n,m)
df["valueComp"] = df["value"]
df["valueComp"] = df["valueComp"].fillna(df[["n", "m"]].min(axis=1))

df

,instance,solver,run,nvertices,nedges,n,m,status,terminationReason,value,totalTime,totalIters,bestTime,bestIter,p,valueComp
0,r_n150_p0.75_nA45_nB45_i2,greedy 2-step (QDEG),0,150,8347,45,45,FEASIBLE,time limit with feasible solution,15.0,2.37915,1,0.002379,0.0,0.75,15.0
1,r_n150_p0.5_nA30_nB45_i1,greedy 2-step (QDEG),0,150,5541,30,45,FEASIBLE,time limit with feasible solution,6.0,1.40436,1,0.001404,0.0,0.50,6.0
2,r_n150_p0.5_nA45_nB45_i0,greedy 2-step (QDEG),0,150,5548,45,45,FEASIBLE,time limit with feasible solution,10.0,1.89802,1,0.001898,0.0,0.50,10.0
3,r_n150_p0.75_nA30_nB45_i2,greedy 2-step (QDEG),0,150,8343,30,45,FEASIBLE,time limit with feasible solution,12.0,1.91425,1,0.001914,0.0,0.75,12.0
4,r_n150_p0.75_nA45_nB30_i2,greedy 2-step (QDEG),0,150,8354,45,30,UNKNOWN,unknown,NaN,0.13721,1,NaN,NaN,0.75,30.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,r_n150_p0.5_nA30_nB30_i2,greedy 1-step,0,150,5522,30,30,FEASIBLE,time limit with feasible solution,7.0,4.08560,1,0.004086,0.0,0.50,7.0
248,r_n150_p0.5_nA45_nB45_i2,greedy 1-step,0,150,5526,45,45,UNKNOWN,unknown,NaN,2.93104,1,NaN,NaN,0.50,45.0
249,r_n150_p0.5_nA30_nB30_i0,greedy 1-step,0,150,5548,30,30,FEASIBLE,time limit with feasible solution,7.0,4.12243,1,0.004122,0.0,0.50,7.0
250,r_n150_p0.25_nA30_nB30_i2,greedy 1-step,0,150,2797,30,30,FEASIBLE,time limit with feasible solution,3.0,2.35562,1,0.002356,0.0,0.25,3.0
251,r_n150_p0.5_nA30_nB45_i0,greedy 1-step,0,150,5548,30,45,FEASIBLE,time limit with feasible solution,6.0,4.31270,1,0.004313,0.0,0.50,6.0

## Best

In [2]:
# Pivot dataframe
df2 = df.pivot(index="instance", columns="solver", values=["value","totalTime"])
n_heurs = int(len(df2.columns)/2)

In [3]:
# Comparison function
def get_winner_heur(row):
    best_heur = None
    min_value = float("inf")
    min_time = float("inf")
    for i in range(n_heurs):
        h = df2.columns[i][1] # get heuristic's name
        j = ("totalTime", h) # get column's name of the bestTime for h
        if (row.iloc[i] < min_value) or (row.iloc[i] == min_value and row[j] < min_time):
            best_heur = h
            min_value = row.iloc[i]
            min_time = row[j]
    return best_heur

def get_winner_value(row):
    min_value = float("inf")
    for i in range(n_heurs):
        if (row.iloc[i] < min_value):
            min_value = row.iloc[i]
    return min_value

In [4]:
df2["winnerValue"] = df2.apply(get_winner_value, axis=1)
df2["winner"] = df2.apply(get_winner_heur, axis=1)

In [5]:
df["winner"] = df.apply(lambda row: row.solver == df2.loc[row.instance].winner, axis=1)
df["tie"] = df.apply(lambda row: (row.value == df2.loc[row.instance].winnerValue), axis=1)

## Summary

In [6]:
df3 = df.groupby(["solver"]).agg(
    {
        "status": [("count", lambda x: (x == "FEASIBLE").sum())],
        "valueComp": [("avg", "mean")],
        "totalTime": [("avg", "mean")],
        "tie": [("%", lambda x: (x == True).sum() / len(x) * 100)],
        "winner": [("%", lambda x: (x == True).sum() / len(x) * 100)],
    }
).reset_index()
df3.columns = ["heuristic", "# solved", "value", "time (ms)", "≥ best (%)", "best (%)"]
df3 = df3.round({
    "value": 1,
    "time (ms)": 2,
})
df3["best (%)"] = df3["best (%)"].round(0).astype(int)
df3["≥ best (%)"] = df3["≥ best (%)"].round(0).astype(int)
df3

               heuristic  # solved  value  time (ms)  ≥ best (%)  best (%)
0          greedy 1-step        16   22.8       3.51          33        11
1    greedy 2-step (DEG)        33   10.5       1.04          36        36
2   greedy 2-step (QDEG)        31   12.0       1.29          39         8
3  greedy 2-step (SQDEG)        32   10.8       1.57          67        36

In [10]:
df3.to_latex("table3.tex", index=False, float_format="%.2f", na_rep="--")